# Generated by Django 3.1.2 on 2020-11-22 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('pub_date', models.DateField(default=None)),
                ('content', models.TextField(default='')),
                ('url', models.CharField(default=None, max_length=255)),
                ('imgurl', models.CharField(default=None, max_length=255)),
                ('score', models.IntegerField(default=None)),
                ('best_new_music', models.BooleanField(default=False, max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_system.artist')),
            ],
        ),
    ]
