# Generated by Django 3.1.2 on 2020-11-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('pub_date', models.CharField(default=None, max_length=255)),
                ('artist', models.CharField(max_length=255, verbose_name='Artist Name')),
                ('content', models.TextField(default='')),
                ('url', models.CharField(default=None, max_length=255)),
                ('score', models.CharField(default=None, max_length=255)),
                ('best_new_music', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
        ),
    ]
