# Generated by Django 3.1.2 on 2020-11-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
