# Generated by Django 3.1.2 on 2020-11-04 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rec_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rec_system.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='best_new_music',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='album',
            name='score',
            field=models.IntegerField(default=None),
        ),
    ]
